from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

import batch_translate_queue as base


ROOT = Path(__file__).resolve().parents[1]
QUEUE_PATH = ROOT / "data" / "new_translations.tsv"

PROTECT_RE = base.PROTECT_RE
TOKEN_RE = base.TOKEN_RE
PRINTF_RE = base.PRINTF_RE
TAG_RE = base.TAG_RE
STRUCTURE_RE = re.compile(
    f"{TAG_RE.pattern}|{base.MALFORMED_TAG_RE.pattern}|{base.ESCAPED_NEWLINE_RE.pattern}",
    re.IGNORECASE,
)

WORD_MAP = dict(base.WORD_MAP)
PHRASE_MAP = dict(base.PHRASE_MAP)
EXACT_MAP = dict(base.EXACT_MAP)

KEEP_WORDS = {
    "AP",
    "CC",
    "CCBD",
    "CN",
    "CPU",
    "DBO",
    "DWC",
    "EP",
    "ESC",
    "EXP",
    "FPS",
    "FFA",
    "GM",
    "GMTool",
    "HoiPoi",
    "HTB",
    "ID",
    "INFO",
    "K",
    "K.O",
    "LFG",
    "LFP",
    "LP",
    "Lv",
    "Lv.",
    "NPC",
    "OK",
    "Online",
    "PK",
    "PROP",
    "PvP",
    "PVP",
    "RP",
    "SP",
    "TMQ",
    "VIP",
    "Wagu",
}

WORD_MAP.update(
    {
        "Account": "账号",
        "action": "操作",
        "Action": "操作",
        "Add": "添加",
        "Admin": "管理员",
        "Age": "年龄",
        "All": "全部",
        "Amount": "数量",
        "Apply": "应用",
        "Aria": "阿利亚",
        "Appearance": "外观",
        "Arena": "竞技场",
        "Auction": "拍卖",
        "Auto": "自动",
        "Autopots": "自动药水",
        "Available": "可用",
        "Back": "返回",
        "Bad": "差",
        "Battle": "战斗",
        "Board": "公告板",
        "Boss": "首领",
        "Budokai": "武道会",
        "Cancel": "取消",
        "Cannot": "无法",
        "Cash": "现金",
        "Category": "分类",
        "Cave": "洞穴",
        "Challenge": "挑战",
        "Character": "角色",
        "Chat": "聊天",
        "Choice": "选择",
        "Class": "职业",
        "Client": "客户端",
        "Close": "关闭",
        "Coins": "硬币",
        "Community": "社区",
        "Confirm": "确认",
        "Confirmation": "确认",
        "Cost": "费用",
        "Count": "数量",
        "Craft": "制作",
        "Crafting": "制作",
        "Current": "当前",
        "Damage": "伤害",
        "Delete": "删除",
        "Description": "说明",
        "Dice": "骰子",
        "Disassemble": "分解",
        "Disconnecting": "断开连接",
        "Dogiball": "时装球",
        "Dragon": "龙",
        "Dungeon": "副本",
        "Effect": "效果",
        "Element": "属性",
        "Elimination": "淘汰",
        "Empty": "空",
        "Enter": "进入",
        "Equipment": "装备",
        "Error": "错误",
        "Event": "活动",
        "Expert": "专家",
        "Extend": "延长",
        "Fearland": "恐惧之地",
        "Final": "决赛",
        "First": "第一",
        "Free": "自由",
        "Friend": "好友",
        "Friends": "好友",
        "Gameguard": "安全程序",
        "Good": "好",
        "Group": "组",
        "Guild": "公会",
        "Hide": "隐藏",
        "Hours": "小时",
        "Inventory": "背包",
        "Item": "道具",
        "Items": "道具",
        "Learned": "已学习",
        "Launcher": "启动器",
        "Level": "等级",
        "Limit": "限制",
        "Lock": "锁定",
        "Loading": "读取中",
        "Mail": "邮件",
        "Mascot": "吉祥物",
        "Max": "最大",
        "Merchant": "商人",
        "Mine": "矿山",
        "Mystery": "神秘",
        "Mix": "混合",
        "Mode": "模式",
        "More": "更多",
        "Name": "名称",
        "Note": "提示",
        "Offline": "离线",
        "Open": "打开",
        "Owner": "拥有者",
        "Party": "队伍",
        "Password": "密码",
        "Policies": "条款",
        "Phy": "物理",
        "Place": "位置",
        "Player": "玩家",
        "Price": "价格",
        "Quest": "任务",
        "Quests": "任务",
        "Rate": "概率",
        "Receive": "领取",
        "Reduced": "减少",
        "Removal": "移除",
        "Remove": "移除",
        "Rename": "改名",
        "Renew": "续期",
        "Repair": "修理",
        "Repaired": "已修理",
        "Requirements": "需求",
        "Resets": "重置",
        "Results": "结果",
        "Retry": "重试",
        "Reward": "奖励",
        "Ribbon": "缎带军",
        "Round": "回合",
        "Scramble": "争夺战",
        "Seal": "封印",
        "Second": "第二",
        "Select": "选择",
        "Selection": "选择",
        "Sell": "出售",
        "Shout": "喊话",
        "Server": "服务器",
        "Share": "分享",
        "Shop": "商店",
        "Show": "显示",
        "Slots": "栏位",
        "Status": "状态",
        "Store": "商店",
        "Style": "风格",
        "Sub": "子",
        "Summon": "召唤",
        "System": "系统",
        "Team": "团队",
        "Tenkaichi": "天下第一",
        "Token": "代币",
        "Tokken": "代币",
        "Trade": "交易",
        "Trigger": "触发",
        "Tutorial": "教程",
        "Underground": "地下",
        "View": "查看",
        "Wait": "等待",
        "Waiting": "等待中",
        "Warehouse": "仓库",
        "Waterfall": "瀑布",
        "Waterway": "水道",
        "Weapons": "武器",
        "Winner": "获胜者",
        "Yahoi": "雅霍伊",
        "Zeni": "索尼",
        "a": "",
        "able": "可以",
        "about": "即将",
        "above": "以上",
        "access": "访问",
        "acquired": "已获得",
        "action": "操作",
        "activate": "激活",
        "active": "激活",
        "added": "添加",
        "all": "全部",
        "allowed": "允许",
        "already": "已经",
        "amount": "数量",
        "an": "",
        "and": "和",
        "another": "另一个",
        "any": "任何",
        "applied": "应用",
        "are": "是",
        "arena": "竞技场",
        "around": "附近",
        "at": "在",
        "attached": "附加",
        "automatically": "自动",
        "available": "可用",
        "be": "被",
        "because": "因为",
        "been": "已",
        "before": "之前",
        "begins": "开始",
        "begun": "开始",
        "being": "正在",
        "blocked": "阻止",
        "boost": "强化",
        "boss": "首领",
        "but": "但",
        "button": "按钮",
        "by": "由",
        "can": "可以",
        "can't": "无法",
        "cannot": "无法",
        "cast": "施放",
        "chance": "几率",
        "change": "更改",
        "changed": "已更改",
        "character": "角色",
        "characters": "角色",
        "checked": "检查中",
        "city": "城市",
        "class": "职业",
        "cleared": "清除",
        "client": "客户端",
        "close": "关闭",
        "color": "颜色",
        "complete": "完成",
        "completed": "已完成",
        "configured": "配置",
        "conditions": "条件",
        "consumed": "消耗",
        "contains": "包含",
        "cost": "费用",
        "could": "无法",
        "couldn't": "无法",
        "crafting": "制作",
        "cry": "哭泣",
        "current": "当前",
        "day": "天",
        "days": "天",
        "decide": "决定",
        "delete": "删除",
        "description": "说明",
        "dialog": "频道",
        "dice": "骰子",
        "different": "不同",
        "disable": "禁用",
        "disabled": "已禁用",
        "disconnected": "断开连接",
        "down": "下",
        "downgraded": "降级",
        "during": "期间",
        "durability": "耐久度",
        "each": "每",
        "effect": "效果",
        "effects": "效果",
        "element": "属性",
        "empty": "空",
        "enable": "启用",
        "ended": "结束",
        "ends": "结束",
        "ensure": "确认",
        "enter": "进入",
        "entered": "已进入",
        "entrance": "入口",
        "error": "错误",
        "event": "活动",
        "exceeded": "超过",
        "exist": "存在",
        "exists": "存在",
        "extra": "额外",
        "fails": "失败",
        "failed": "失败",
        "far": "远",
        "fight": "战斗",
        "final": "决赛",
        "find": "查找",
        "first": "第一",
        "following": "以下",
        "for": "用于",
        "found": "找到",
        "free": "自由",
        "from": "来自",
        "function": "功能",
        "game": "游戏",
        "get": "获得",
        "got": "已",
        "guild": "公会",
        "has": "已",
        "hasn't": "尚未",
        "have": "有",
        "higher": "更高",
        "hour": "小时",
        "if": "如果",
        "in": "在",
        "increase": "增加",
        "increased": "增加",
        "increases": "增加",
        "info": "信息",
        "information": "信息",
        "inserted": "已放入",
        "into": "到",
        "invite": "邀请",
        "is": "是",
        "isn't": "不是",
        "it": "它",
        "joined": "已加入",
        "kick": "踢出",
        "last": "上一条",
        "learn": "学习",
        "leave": "离开",
        "left": "剩余",
        "level": "等级",
        "limit": "限制",
        "locked": "锁定",
        "longer": "更久",
        "lose": "失去",
        "made": "建成",
        "max": "最大",
        "maximum": "最大",
        "meet": "满足",
        "member": "成员",
        "missing": "缺少",
        "more": "更多",
        "move": "移动",
        "moved": "移动",
        "movie": "影片",
        "must": "必须",
        "name": "名称",
        "need": "需要",
        "needed": "需要",
        "new": "新",
        "no": "没有",
        "not": "不",
        "now": "现在",
        "number": "数量",
        "obtain": "获得",
        "occurred": "发生",
        "of": "的",
        "off": "下车",
        "on": "在",
        "once": "一次",
        "one": "一个",
        "open": "打开",
        "or": "或",
        "other": "其他",
        "out": "出",
        "over": "结束",
        "owner": "拥有者",
        "panel": "面板",
        "password": "密码",
        "permission": "权限",
        "play": "游玩",
        "player": "玩家",
        "players": "玩家",
        "possible": "可以",
        "price": "价格",
        "problem": "问题",
        "progress": "进度",
        "quest": "任务",
        "rate": "概率",
        "reached": "已达到",
        "reaching": "到达",
        "rebuild": "重建",
        "receive": "领取",
        "recommendations": "推荐",
        "recover": "恢复",
        "reduced": "减少",
        "registered": "已报名",
        "registration": "报名",
        "removed": "移除",
        "renaming": "改名",
        "reply": "回复",
        "required": "需要",
        "requires": "需要",
        "reset": "重置",
        "reward": "奖励",
        "run": "运行",
        "runs": "运行",
        "sacrifice": "辅助",
        "schedule": "日程",
        "scramble": "争夺战",
        "seal": "封印",
        "select": "选择",
        "selection": "选择",
        "sell": "出售",
        "share": "分享",
        "shop": "商店",
        "skipped": "跳过",
        "skip": "跳过",
        "slowly": "缓慢",
        "sold": "已出售",
        "spawn": "复活",
        "starts": "开始",
        "state": "状态",
        "status": "状态",
        "stop": "站",
        "summon": "召唤",
        "summoned": "已召唤",
        "sure": "确定",
        "system": "系统",
        "takes": "需要",
        "tap": "点击",
        "team": "团队",
        "that": "该",
        "the": "",
        "their": "他们的",
        "them": "它们",
        "there": "有",
        "this": "此",
        "to": "到",
        "too": "太",
        "trade": "交易",
        "transfer": "转移",
        "trying": "尝试",
        "until": "直到",
        "up": "上",
        "upgraded": "已升级",
        "use": "使用",
        "used": "使用",
        "user": "用户",
        "was": "是",
        "when": "当",
        "while": "时",
        "who": "的玩家",
        "will": "将",
        "win": "获胜",
        "with": "使用",
        "without": "不使用",
        "won": "获胜",
        "won't": "不会",
        "world": "世界",
        "wrong": "错误",
        "yet": "尚未",
        "you": "你",
        "your": "你的",
        "yourself": "自己",
    }
)

PHRASE_MAP.update(
    {
        "Are you sure": "确定",
        "Auto Popo": "自动波波",
        "Auction House": "拍卖行",
        "Buff Removal": "移除增益",
        "CC Battle Dungeon": "CC战斗副本",
        "Change Item PROP": "更改道具属性",
        "Character Server": "角色服务器",
        "Chat Server": "聊天服务器",
        "Community Server": "社区服务器",
        "Connection Failed": "连接失败",
        "Cooldown Reduced": "冷却减少",
        "Dragon Cave": "龙洞",
        "Drop Rate": "掉落率",
        "Dungeon Choice Rules": "副本选择规则",
        "Free-for-all": "自由拾取",
        "Free for all": "自由拾取",
        "Game Check": "游戏检查",
        "Guild Rename": "公会改名",
        "Hit ESC to skip": "按 ESC 跳过",
        "HoiPoi Mine": "HoiPoi矿山",
        "Item inserted": "道具已放入",
        "No sacrifice item required": "不需要辅助道具",
        "On failure": "失败时",
        "On success": "成功时",
        "Red Pants HQ": "红裤军总部",
        "Red Ribbon HQ": "红缎带军总部",
        "Success Rate": "成功率",
        "Underground Waterway": "地下水道",
        "West City": "西都",
        "Yahoi Fortress": "雅霍伊要塞",
        "accept the following item": "接受以下道具",
        "all finished": "全部结束",
        "and will be moved to the entrance": "并将移动到入口",
        "bring you back": "让你复活",
        "can open": "可以打开",
        "change channel": "切换频道",
        "choose the PROP you want": "选择你想要的属性",
        "city NPCs": "城市NPC",
        "during the event window": "在活动窗口期间",
        "event ends": "活动结束",
        "event window": "活动窗口",
        "extra XP": "额外经验",
        "for schedule info": "查看日程信息",
        "from the status bar": "从状态栏",
        "in progress": "进行中",
        "is being checked": "正在检查",
        "last whisper": "上一条密语",
        "not configured": "未配置",
        "of the item": "道具的",
        "on this server": "在此服务器上",
        "open this panel": "打开此面板",
        "progress and will be moved": "进度并将被移动",
        "registered for this event": "报名此活动",
        "side panel": "侧边面板",
        "the event ends": "活动结束",
        "the next stop": "下一站",
        "to cancel": "取消",
        "to disable": "禁用",
        "to enable": "启用",
        "to leave party": "离开队伍",
        "to select": "选择",
        "you are teleported automatically": "你会被自动传送",
        "you can": "你可以",
        "you have": "你已",
        "you want": "你想",
        "you'll": "你将",
        "you're": "你",
        "you've": "你已",
    }
)

EXACT_MAP.update(
    {
        "Auction House": "拍卖行",
        "Cannot open Mail or Auction House while in combat.": "无法在战斗中打开邮件或拍卖行。",
        "Mail and Auction House will close automatically when you enter combat.": "进入战斗时，邮件和拍卖行会自动关闭。",
    }
)

SEGMENT_EXACT = {
    "N/A": "N/A",
    "K.O": "K.O",
    "Name :": "名称：",
    "Name:": "名称：",
    "Trade:": "交易：",
    "Trade": "交易",
    "Challenge": "挑战",
    "Reward": "奖励",
    "Team": "团队",
    "Final": "决赛",
    "Semi Final": "半决赛",
    "Group A": "A组",
    "Group B": "B组",
    "Coins": "硬币",
    "Can't Extend": "无法延长",
    "AP is consumed only during accelerated flying.": "AP只会在加速飞行时消耗。",
    "It regenerates while you fly slowly or while on ground.": "慢速飞行或在地面时会恢复。",
    "Your account has been created and should": "你的账号已创建，应该",
    "now have access to Dragon Ball Online": "现在可以进入龙珠Online",
    "You've failed to connect to": "连接失败：",
    "the authentication server.": "验证服务器。",
    "Please try again in a few minutes.": "请几分钟后再试。",
    "Please try again later.": "请稍后再试。",
    "You're about to change channel.": "你即将切换频道。",
    "When the player dies he can re-spawn": "玩家死亡后可以复活",
    "to his chosen Popo Stone.": "到已选择的波波石。",
    "Change your Home Teleport": "更改你的回城传送",
    "Location to this Area?": "位置到此区域？",
    "Are you sure to cancel the registration?": "确定取消报名吗？",
    "Tenkaichi Budokai": "天下第一武道会",
    "You are a solo %s": "你是单人参赛者 %s",
    "%s final match started.": "%s 决赛已开始。",
    "%s is over.": "%s 已结束。",
    "You're in a Party %s": "你在队伍中 %s",
    "%d month %d day %s %d:%02d": "%d月%d日 %s %d:%02d",
    "Tenkaichi Budokai Nr. %d": "第%d届天下第一武道会",
    "Can't join Budokai.": "无法参加武道会。",
    "Budokai Receptionist": "武道会接待员",
    "Tenkaichi": "天下第一",
    "Budokai Menu": "武道会菜单",
    "Budokai Disabled": "武道会已禁用",
    "Budokai Finals": "武道会决赛",
    "Budokai Qualifiers": "武道会预选赛",
    "Budokai Match": "武道会比赛",
    "Budokai Preliminaries": "武道会预赛",
    "Budokai is in progress.": "武道会进行中。",
    "Budokai isn't open.": "武道会未开放。",
    "Already joined Budokai.": "已经加入武道会。",
    "Unable while in Budokai.": "武道会期间无法进行。",
    "Unable to join Budokai during Scramble event.": "争夺战活动期间无法参加武道会。",
    "%s recommendations.": "%s 推荐。",
    "%s %s %s has begun.": "%s %s %s 已开始。",
    "Tournament %s is starting.": "锦标赛 %s 即将开始。",
    "%s all finished": "%s 全部结束",
    "That was a great battle!": "这是一场精彩的战斗！",
    "You'll be moved out soon!": "你很快会被移出！",
    "What's this? Ladies and gentlemen we finally have a winner!": "各位观众，我们终于有获胜者了！",
    "That was amazing, congratulations!": "太精彩了，恭喜！",
    "What an amazing fight!": "真是一场精彩的战斗！",
    "It was worth seeing!": "这场值得一看！",
    "Next fight will start soon.": "下一场战斗即将开始。",
    "I wish you good luck and hope you win!": "祝你好运，愿你获胜！",
    "%s team member %s must decide %d : %d.": "%s 队伍成员 %s 必须决定 %d：%d。",
    "Event window open. Registered: %d. Use Register in the side panel.": "活动窗口已开放。已报名：%d。请在侧边面板报名。",
    "%d players registered. Teleport starts when the match begins.": "已有 %d 名玩家报名。比赛开始时会传送。",
    "Free-for-all PvP arena event.": "自由混战PvP竞技场活动。",
    "Open this panel and tap Register during the event window.": "活动窗口期间打开此面板并点击报名。",
    "With 2+ players you are teleported automatically.": "2名以上玩家报名后会自动传送。",
    "Fight until the event ends.": "战斗直到活动结束。",
    "Ask city NPCs for schedule info.": "向城市NPC询问日程信息。",
    "You are already registered for this event.": "你已经报名此活动。",
    "The arena is not configured on this server.": "此服务器尚未配置竞技场。",
    "%d Elimination Round %u": "%d 淘汰赛第 %u 轮",
    "Semi Final %u": "半决赛 %u",
    "%u I %u W %u L": "%u 场 %u 胜 %u 负",
    "Team Registration Cancel": "团队报名取消",
    "Are you sure to Cancel?": "确定取消吗？",
    "Click icon to disable/enable or remove buff": "点击图标禁用、启用或移除增益",
    "Buff Removal": "移除增益",
    "Remove Buff: %s ?": "移除增益：%s？",
    "INFO: Autopots can't be removed but you can": "提示：自动药水无法移除，但你可以",
    "disable/enable them.": "禁用或启用它们。",
    "Stopping Bus": "巴士停车",
    "Get off before reaching the next stop.": "到达下一站前下车。",
    "Get off the Bus?": "要下车吗？",
    "Participants who enter CC Battle Dungeon will fight enemies on each floor.": "进入CC战斗副本的参与者会在每层与敌人战斗。",
    "Each floor's difficulty is different. Every 5th floor will be a boss floor, and once boss is defeated you have the option to take reward and leave or carry on.": "每层难度不同。每5层是首领层，击败首领后可以领取奖励离开，也可以继续挑战。",
    "Recommended Level: 50": "推荐等级：50",
    "Higher floors give better rewards!": "层数越高奖励越好！",
    "Leave CCBD Dungeon": "离开CCBD副本",
    "Current Floor: %d.": "当前层数：%d。",
    "You'll lose all progress": "你将失去全部进度",
    "and will be moved to the entrance.": "并被移动到入口。",
    "Leave CCBD?": "离开CCBD？",
    "Dungeon Choice Rules": "副本选择规则",
    "Receive item, but leave dungeon.": "领取道具并离开副本。",
    "Continue, but no item yet.": "继续挑战，但暂不领取道具。",
    "You have complete the dungeon.": "你已完成副本。",
    "You will get a reward and": "你将获得奖励",
    "will be moved to the entrance.": "并被移动到入口。",
    "Continue to next floor for better reward?": "继续到下一层以获得更好奖励？",
    "Accept the following item?": "接受以下道具？",
    "You'll leave the dungeon.": "你将离开副本。",
    "Change Item PROP": "更改道具属性",
    "Selected Element: %s": "已选属性：%s",
    "Price: %s Zeni": "价格：%s 索尼",
    "Success Rate: %d%%": "成功率：%d%%",
    "On success, %s PROP is applied.": "成功时，%s 属性会被应用。",
    "On failure, PROP is cleared.": "失败时，属性会被清除。",
    "No sacrifice item is required.": "不需要辅助道具。",
    "Click to select this element for your item.": "点击为你的道具选择此属性。",
    "If it fails, the item PROP is cleared.": "如果失败，道具属性会被清除。",
    "Item inserted.": "道具已放入。",
    "Click an element slot to choose the PROP you want.": "点击属性栏位选择你想要的属性。",
    "No sacrifice item required.": "不需要辅助道具。",
    "VIP members can open Change Attributes remotely from the status bar.": "VIP成员可以从状态栏远程打开属性更改。",
    "Could not open VIP menu. Rebuild the client and ensure vipremotehubgui.frm is in the gui folder.": "无法打开VIP菜单。请重建客户端，并确认 vipremotehubgui.frm 位于 gui 文件夹。",
    "Cooldown Reduced by %d%%": "冷却减少 %d%%",
    "Increase Drop Rate by %d%%": "掉落率增加 %d%%",
    "obtain %d%% extra XP": "获得 %d%% 额外经验",
    "Share %d RP": "分享 %d RP",
    "Title %s acquired.": "获得称号 %s。",
    "Failed to connect to": "连接失败：",
    "Character Server.": "角色服务器。",
    "Returning to the Lobby.": "正在返回大厅。",
    "Do you wish to Log Out?": "要登出吗？",
    "Command: %s": "命令：%s",
    "Lock": "锁定",
    "Unlock": "解锁",
    "Shout": "喊话",
    "Trade: %s": "交易：%s",
    "Connection Failed": "连接失败",
    "Failed to connect to a chat server.": "连接聊天服务器失败。",
    "try again later.": "请稍后再试。",
    "Community Server": "社区服务器",
    "Dragon Ball Online Community Server": "龙珠Online社区服务器",
    "is being checked": "正在检查",
    "You can access the game later.": "稍后可以进入游戏。",
    "Dragon Ball Online is Offline.": "龙珠Online当前离线。",
    "Hit ESC to skip": "按 ESC 跳过",
    "%s skipped the movie.": "%s 跳过了影片。",
    "Client error, Re-run the Launcher.": "客户端错误，请重新运行启动器。",
    "Sorry! (Disconnecting)": "抱歉！正在断开连接",
    "#%d Tournament Winner: %s %s %s %s.": "#%d 锦标赛获胜者：%s %s %s %s。",
    "You're renaming the Guild.": "你正在为公会改名。",
    "Renaming takes": "改名需要",
    "Rename the Guild?": "为公会改名？",
    "Missing Popo Stone.": "缺少波波石。",
}

WORD_MAP.update(
    {
        "Balance": "余额",
        "Bargain": "议价",
        "Boost": "强化",
        "Break": "中断",
        "Camera": "镜头",
        "Card": "卡片",
        "Champion": "冠军",
        "Chances": "几率",
        "Collection": "收集",
        "Compensation": "补偿",
        "Converted": "转换",
        "Deletion": "删除",
        "Deposit": "存入",
        "Difficulty": "难度",
        "Dismiss": "踢出",
        "Donate": "捐献",
        "Duel": "决斗",
        "Dyeing": "染色",
        "Earned": "获得",
        "End": "结束",
        "Expiration": "期限到期",
        "Fabric": "布料",
        "Fee": "费用",
        "Feature": "功能",
        "Gift": "礼物",
        "Hard": "困难",
        "Identify": "鉴定",
        "Incorrect": "不正确",
        "Input": "输入",
        "Instruction": "说明",
        "Legendary": "传说",
        "Login": "登录",
        "Logo": "标志",
        "Mailbox": "邮箱",
        "Materials": "材料",
        "Minimap": "小地图",
        "Obtained": "已获得",
        "Options": "选项",
        "Order": "顺序",
        "Passive": "被动",
        "Perfect": "完美",
        "Point": "点数",
        "Prize": "奖励",
        "Race": "种族",
        "Rating": "评级",
        "Reject": "拒绝",
        "Resize": "调整大小",
        "Room": "房间",
        "Roll": "掷骰",
        "Sale": "出售",
        "Save": "保存",
        "Scenario": "剧情",
        "Search": "搜索",
        "Seed": "种子席位",
        "Sign": "报名",
        "Sorry": "抱歉",
        "Spam": "刷屏",
        "Stores": "商店",
        "Slot": "栏位",
        "Text": "文本",
        "Tokens": "代币",
        "Trash": "丢弃",
        "Turn": "切换",
        "Uniform": "道服",
        "Usage": "支出",
        "Withdraw": "取出",
        "Wood": "木材",
        "Would": "是否",
        "Owned": "拥有",
        "owned": "拥有",
        "Suspended": "暂停",
        "Extended": "延长",
        "Moving": "移动",
        "Overwrite": "覆盖",
        "Refund": "返还",
        "Feature": "功能",
        "Changes": "变更",
        "Qualify": "取得资格",
        "So": "所以",
        "Our": "我方",
        "Today": "今天",
        "Challenger": "挑战者",
        "Setup": "设置",
        "Low": "低",
        "Usage": "支出",
    }
)

SEGMENT_EXACT.update(
    {
        "What is this? Ladies and gentlemen we finally have a winner!": "各位观众，我们终于有获胜者了！",
        "What is this?": "这是怎么回事？",
        "Ladies and gentlemen we finally have a winner!": "各位观众，我们终于有获胜者了！",
        "It is time to fight": "战斗时间到了",
        "Win : get up to 500 points": "胜利：最多获得500点",
        "1 Learn how to fight": "1 学习战斗方式",
        "+2 points if dojo imprint acquisition": "获得道场印记时 +2 点",
        "2 points to go": "前进需要2点",
        "Tension Points 300 bet +8": "下注斗志点数300，+8",
        "Cannot create a party in a fight": "战斗中无法创建队伍",
        "Dojo Players": "道场玩家",
        "will send a challenge.": "将发送挑战。",
        "When the challenge is accepted": "挑战被接受后",
        "you will have to fight.": "你必须战斗。",
        "When you send a challenge": "当你发送挑战时",
        "You must win": "你必须获胜",
        "Or be ready to laughed at": "否则就等着被嘲笑",
        "Know your enemy!": "了解你的敌人！",
        "Matches for Zeni": "索尼比赛",
        "(Match might be rejected.)": "（比赛可能被拒绝。）",
        "%s Challenge from Dojo": "来自道场的 %s 挑战",
        "Accept the challenge to prove your worth": "接受挑战，证明你的价值",
        "Fight for the Dojo's fate": "为道场命运而战",
        "If you Reject": "如果你拒绝",
        "You cannot win any Zeni.": "你无法获得任何索尼。",
        "Required": "需要",
        "%s Qualified": "%s 已取得资格",
        "Good luck in the Tournament.": "祝你在锦标赛中好运。",
        "Renaming takes": "改名需要",
        "1day.": "1天。",
        "%s 1day.": "%s 1天。",
        "%s Team Result ( %u )": "%s 团队结果（%u）",
        "%s Score Results %u": "%s 分数结果 %u",
        "%s Killed %s ": "%s 击败了 %s ",
        "10s %s goes into the arena": "10秒后 %s 进入竞技场",
        "Paid %u": "已支付 %u",
        "Command: %s": "命令：%s",
        "Do not Spam": "不要刷屏",
        "Do not Spam the Shout": "不要刷喊话",
        "Zeni Owned": "拥有索尼",
        "Tokens owned": "拥有代币",
        "Remote Stores": "远程商店",
        "Mailbox Access": "邮箱访问",
        "Reject": "拒绝",
        "See Instruction": "查看说明",
        "Loading": "读取中",
        "Order": "顺序",
        "Enter Text to Summon Shenron": "输入文本召唤神龙",
        "Dragon Ball Collection Period is not in progress": "龙珠收集期间尚未开始",
        "Dragon Ball Collection Period is in progress": "龙珠收集期间进行中",
        "Since the start, %d time has elapsed.": "自开始以来，已经过 %d 次。",
        "Excessive play can disturb their daily life.": "过度游戏会影响日常生活。",
        "Chat Resize": "聊天窗口调整",
        "The Dice will Roll": "将掷骰子",
        "Get Materials": "获得材料",
        "Chances of obtaining the maximum rating:%.2f%%": "获得最高评级的几率：%.2f%%",
        "Fabric": "布料",
        "Wood": "木材",
        "Not Converted": "未转换",
        "Material Degradation": "材料分解",
        "Trash": "丢弃",
        "Uniform dyeing": "道服染色",
        "Would you like to end uniform staining?": "是否结束道服染色？",
        "Dyeing": "染色",
        "Make sure that you have permission.": "请确认你拥有权限。",
        "Battle Deposit": "战斗存入",
        "Battle Withdraw": "战斗取出",
        "Deposit": "存入",
        "Withdraw": "取出",
        "Donate": "捐献",
        "Get more benefits from more features.": "功能越多，获得的福利越多。",
        "Requirements:": "需求：",
        "Points needed: %d": "需要点数：%d",
        "Add Feature?": "添加功能？",
        "Changes:": "变更：",
        "Feature: %s": "功能：%s",
        "Dojo Feature Changed.": "道场功能已更改。",
        "Tournament Players": "锦标赛选手",
        "Players who prove to be the best.": "证明自己最强的玩家。",
        "Will go to the 32 qualification spots": "将进入32个资格席位",
        "Fight to Qualify.": "通过战斗取得资格。",
        "All players": "所有玩家",
        "Check the following:": "请确认以下内容：",
        "This is the best Tournament": "这是最强锦标赛",
        "in the world.": "在世界范围内。",
        "So you better make sure": "所以请确认",
        "You are here!": "你已经在这里！",
        "No Logo": "无标志",
        "Other Logo": "其他标志",
        "Our Logo": "我方标志",
        "Lv.4:Update": "Lv.4：更新",
        "Lv.6:Update": "Lv.6：更新",
        "Lv.8:Update": "Lv.8：更新",
        "Teleport or Exit": "传送或退出",
        "Earned %d Mudosa": "获得 %d 武道寺点数",
        "Earned %d Dragon Ball": "获得 %d 龙珠",
        "Rating": "评级",
        "Difficulty Level": "难度等级",
        "Scenario Info": "剧情信息",
        "DWC Scenario List": "DWC剧情列表",
        "Cannot Duel Blacklisted Player.": "无法与黑名单玩家决斗。",
        "Duel Request": "决斗请求",
        "You are being challenged": "你收到了挑战",
        "to a Duel.": "进行决斗。",
        "Challenger: %s": "挑战者：%s",
        "Capsule Earned": "获得胶囊",
        "Exit Game": "退出游戏",
        "Do you wish to exit DBO?": "要退出DBO吗？",
        "Thanks for playing": "感谢游玩",
        "Quest Point Shop": "任务点数商店",
        "Search": "搜索",
        "Mix Machine Setup Fee": "混合机器设置费用",
        "Identify the item.": "鉴定该道具。",
        "Not Enough Tokens": "代币不足",
        "Difficulty": "难度",
        "Current Weight %d": "当前重量 %d",
        "Weight Limit %d": "重量限制 %d",
        "Weight : %d": "重量：%d",
        "Race(%s)BUFF Apply this channel.": "种族（%s）增益应用于此频道。",
        "Save Character": "保存角色",
        "Race": "种族",
        "Check Point": "检查点",
        "Can Change Uniform": "可更改道服",
        "Tournament Seed": "锦标赛种子席位",
        "Current Tokens": "当前代币",
        "Identify Item": "鉴定道具",
        "Start Roll": "开始掷骰",
        "Roll too Low": "点数太低",
        "Difficulty: Hard": "难度：困难",
        "Hard": "困难",
        "Party Search": "队伍搜索",
        "Party Charm": "队伍护符",
        "Stop using charm?": "停止使用护符？",
        "By Rating": "按品质",
        "Unset Target 1": "取消目标1",
        "Unset Target 2": "取消目标2",
        "Unset Target 3": "取消目标3",
        "Fee: %s Zeni": "费用：%s 索尼",
        "Turn on OR off the quest list window.": "开启或关闭任务列表窗口。",
        "Scenario Quest": "剧情任务",
        "Cannot share, wrong Race: %s": "无法分享，种族错误：%s",
        "Save: %s": "保存：%s",
        "Remote Identify": "远程鉴定",
        "Quest Search": "任务搜索",
        "%s restored %d EP.": "%s 恢复 %d EP。",
        "%s restored %d LP.": "%s 恢复 %d LP。",
        "Turn On/Off": "开启/关闭",
        "Turn ON/OFF for Quest search": "开启/关闭任务搜索",
        "No Prize": "无奖励",
        "Second Place Prize": "第二名奖励",
        "Team Second Place Prize": "团队第二名奖励",
        "World Martial Arts Tournament Seed Notice": "天下第一武道会种子席位通知",
        "Fee set not available.": "无法设置费用。",
        "Moving items": "移动道具",
        "Move the selected item to the capsule kit.": "将选中道具移动到胶囊工具包。",
        "When moved into the capsule kit": "移动到胶囊工具包后",
        "and the same item already exists": "如果已有相同道具",
        "the durability get increased.": "耐久度会增加。",
        "Are you sure you want to move an item?": "确定要移动道具吗？",
        "Overwrite this Slot?": "覆盖此栏位？",
        "Save location to slot?": "将位置保存到栏位？",
        "Item Expiration": "道具期限到期",
        "The item's time limit has expired.": "该道具时限已到期。",
        "Pay to extend it is use?": "支付费用延长使用时间？",
        "All Skills will be Reset": "所有技能将被重置",
        "Use Item: %s": "使用道具：%s",
        "SP Saved: %u": "保存SP：%u",
        "Refund: 120,000 Zeni": "返还：120,000 索尼",
        "Refund Zeni for all that you relearn": "重新学习时返还所有索尼",
        "No SP needed for Reset.": "重置不需要SP。",
        "%s Expired and Use is Suspended": "%s 已过期，使用已暂停",
        "This item can be Extended": "此道具可以延长",
    }
)


def protect_tokens(text: str) -> tuple[str, list[str]]:
    tokens: list[str] = []

    def repl(match: re.Match[str]) -> str:
        tokens.append(match.group(0))
        return f"{{{{{len(tokens) - 1}}}}}"

    return STRUCTURE_RE.sub(repl, text), tokens


def restore_tokens(text: str, tokens: list[str]) -> str:
    for index, token in enumerate(tokens):
        text = text.replace(f"{{{{{index}}}}}", token)
    return text


def translate_visible_segment(segment: str) -> str:
    if not segment or not segment.strip():
        return segment
    prefix = segment[: len(segment) - len(segment.lstrip())]
    suffix = segment[len(segment.rstrip()) :]
    core = segment.strip()
    raw_core = expand_contractions(core)
    if raw_core in SEGMENT_EXACT:
        return f"{prefix}{SEGMENT_EXACT[raw_core]}{suffix}"
    if raw_core in EXACT_MAP:
        return f"{prefix}{EXACT_MAP[raw_core]}{suffix}"
    printf_tokens: list[str] = []

    def protect_printf(match: re.Match[str]) -> str:
        printf_tokens.append(match.group(0))
        return f"@@P{len(printf_tokens) - 1}@@"

    core = PRINTF_RE.sub(protect_printf, core)
    core = expand_contractions(core)
    if core in SEGMENT_EXACT:
        return f"{prefix}{restore_printf(SEGMENT_EXACT[core], printf_tokens)}{suffix}"
    if core in EXACT_MAP:
        return f"{prefix}{restore_printf(EXACT_MAP[core], printf_tokens)}{suffix}"
    core = normalize_punctuation(core)
    core = expand_contractions(core)
    core = replace_possessives(core)
    for source, target in sorted(PHRASE_MAP.items(), key=lambda item: len(item[0]), reverse=True):
        if not source:
            continue
        core = re.sub(rf"(?<![A-Za-z0-9]){re.escape(source)}(?![A-Za-z0-9])", target, core, flags=re.IGNORECASE)
    core = re.sub(r"\b(\d+)(st|nd|rd|th)\b", r"第\1", core, flags=re.IGNORECASE)
    core = re.sub(r"\b([A-Za-z][A-Za-z']*)\b", replace_word, core)
    core = cleanup(core)
    core = restore_printf(core, printf_tokens)
    return f"{prefix}{core}{suffix}"


def restore_printf(text: str, tokens: list[str]) -> str:
    for index, token in enumerate(tokens):
        text = text.replace(f"@@P{index}@@", token)
    return text


def replace_possessives(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        owner = translate_word(match.group(1))
        return f"{owner}的"

    return re.sub(r"\b([A-Za-z][A-Za-z]*)'s\b", repl, text)


def expand_contractions(text: str) -> str:
    replacements = {
        "What's": "What is",
        "what's": "what is",
        "It's": "It is",
        "it's": "it is",
        "You'll": "You will",
        "you'll": "you will",
        "You're": "You are",
        "you're": "you are",
        "You've": "You have",
        "you've": "you have",
        "You'll": "You will",
        "Don't": "Do not",
        "don't": "do not",
        "Doesn't": "Does not",
        "doesn't": "does not",
        "Can't": "Cannot",
        "can't": "cannot",
        "Won't": "Will not",
        "won't": "will not",
        "Isn't": "Is not",
        "isn't": "is not",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def replace_word(match: re.Match[str]) -> str:
    return translate_word(match.group(1))


def translate_word(word: str) -> str:
    if re.fullmatch(r"P\d+", word):
        return word
    if word in KEEP_WORDS or re.fullmatch(r"RO\d+|[A-Z]{1,3}\d*", word):
        return word
    for key in (word, word.lower(), word.title(), word.upper()):
        value = WORD_MAP.get(key)
        if value is not None:
            return value
    if word[:1].isupper():
        return word
    return ""


def normalize_punctuation(text: str) -> str:
    return (
        text.replace("•", "-")
        .replace("’", "'")
        .replace("“", '"')
        .replace("”", '"')
        .replace("–", "-")
        .replace("—", "-")
    )


def cleanup(text: str) -> str:
    replacements = {
        "你 是": "你已",
        "你是 已经": "你已",
        "是 不": "未",
        "是 未": "未",
        "的 的": "的",
        "到 到": "到",
        "使用 到": "使用",
        "点击 到": "点击",
        "打开 此": "打开此",
        "此 道具": "此道具",
        "该 道具": "该道具",
        "等级 ：": "等级：",
        "价格 ：": "价格：",
        "概率 ：": "概率：",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"\s+([，。！？；：、）])", r"\1", text)
    text = re.sub(r"([（])\s+", r"\1", text)
    text = re.sub(r"([\u4e00-\u9fff])\s+([\u4e00-\u9fff])", r"\1\2", text)
    text = re.sub(r"([\u4e00-\u9fff])\s+([A-Z]{1,5})(?=\s|$|[，。！？；：、)])", r"\1\2", text)
    text = re.sub(r"([A-Z]{1,5})\s+([\u4e00-\u9fff])", r"\1\2", text)
    text = text.replace(": ", "：").replace(" :", "：")
    text = text.replace(" ,", "，").replace(" .", "。").replace(" ?", "？").replace(" !", "！")
    text = re.sub(r"([\u4e00-\u9fff])\.($|\s|\{\{)", r"\1。\2", text)
    text = re.sub(r"([\u4e00-\u9fff]),", r"\1，", text)
    text = re.sub(r"([\u4e00-\u9fff])\?", r"\1？", text)
    text = re.sub(r"([\u4e00-\u9fff])!", r"\1！", text)
    return text.strip()


def translate_text(text: str) -> str:
    protected, tokens = protect_tokens(text)
    parts = TOKEN_RE.split(protected)
    separators = TOKEN_RE.findall(protected)
    output: list[str] = []
    for index, part in enumerate(parts):
        output.append(translate_visible_segment(part))
        if index < len(separators):
            output.append(separators[index])
    return restore_tokens("".join(output), tokens)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Format-safe bulk retranslation for data/new_translations.tsv")
    parser.add_argument("--in-place", action="store_true", help="Overwrite data/new_translations.tsv")
    parser.add_argument("--out", type=Path, default=ROOT / "reports" / "internal" / "queue_format_safe_preview.tsv")
    return parser.parse_args()


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    args = parse_args()
    out_path = QUEUE_PATH if args.in_place else args.out
    if not out_path.is_absolute():
        out_path = ROOT / out_path
    with QUEUE_PATH.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        rows = list(reader)
        fieldnames = reader.fieldnames or []
    if not fieldnames:
        raise SystemExit("empty queue")

    source_col = fieldnames[3]
    target_col = fieldnames[5]
    changed = 0
    for row in rows:
        source = row.get(source_col) or ""
        translated = translate_text(source)
        if translated.strip() and translated != row.get(target_col, ""):
            row[target_col] = translated
            changed += 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter="\t", lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
    print(f"changed={changed}")
    print(f"path={out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
